[project]
name = 'Decentralized-Abstract-Concept-Ecosystem'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.idea-evolution]
path = 'contracts/idea-evolution.clar'
clarity_version = 2
epoch = 2.5

[contracts.memetic-resilience]
path = 'contracts/memetic-resilience.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
